AllCops:
  TargetRubyVersion: 2.5.1
  DisplayCopNames: true
  Exclude:
    - bin/*
    - vendor/bundle/**/*
    - node_modules/**/*
    - db/schema.rb
    - .licenses/**/*
Rails:
  Enabled: true
Metrics:
  Exclude:
    - db/migrate/*
    - Rakefile
    - Gemfile
    - config/**/*
    - spec/**/*
    - lib/tasks/**/*
Layout:
  Exclude:
    - config/environments/*
Style:
  Exclude:
    - spec/*_helper.rb
Style/BlockComments:
  Exclude:
    - config/**/*
    - spec/**/*
Style/Documentation:
  Enabled: false
