plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.3
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - .licenses/**/*
