default: &default
  site:
    default_domain: <%= ENV['SITE_DEFAULT_DOMAIN'] || 'tgdf.tw' %>
    name: <%= ENV['SITE_NAME'] || '台北遊戲開發者論壇' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
