default: &default
  site:
    default_domain: <%= ENV['SITE_DEFAULT_DOMAIN'] || 'tgdf.tw' %>
  news:
    latest:
      size: <%= (ENV['NEWS_LATEST_SIZE'] || 5).to_i %>

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

production:
  <<: *default
