name: Containerize

on:
  push:
    branches:
      - main

env:
  RUBY_VERSION: '3.2.1'
  RAILS_ENV: production
  SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
  REGISTRY: ghcr.io
  IMAGE_NAME: tgdf/official-site

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
    - run: yarn install
    - run: bundle exec rake assets:precompile
    - name: Archive precompiled assets
      uses: actions/upload-artifact@v3
      with:
        name: assets
        path: public/
        retention-days: 7
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: assets
    permissions:
      contents: read
      packages: write
    outputs:
      sha-tag: ${{ fromJSON(steps.meta.outputs.json).tags[1] }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download precompiled assets
        uses: actions/download-artifact@v3
        with:
          name: assets
          path: public/

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=branch

      - name: Add short SHA information
        id: commit
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            REVISION=${{ steps.commit.outputs.sha_short }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL'

  trigger-deployment:
    needs: build-and-push-image
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        environment: [beta,production]
    uses: ./.github/workflows/deployment.yml
    with:
      image: ${{ needs.build-and-push-image.outputs.sha-tag }}
      environment: ${{ matrix.environment }}
    secrets: inherit
