name: Containerize

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: '2.7.5'
  RAILS_ENV: production
  SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - run: yarn install
    - run: bundle exec rake assets:precompile
    - name: Archive precompiled assets
      uses: actions/upload-artifact@v3
      with:
        name: assets
        path: public/
        retention-days: 7
