name: Deploy

on:
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string

env:
  TASK_DEFINITION: 'tgdf-beta'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.DEPLOY_IAM_ROLE }}
        aws-region: ap-northeast-1

    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition $TASK_DEFINITION --query taskDefinition > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: web
        image: ${{ inputs.image }}
