name: Rails

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: '2.7.5'
  RAILS_ENV: test
  DATABASE_URL: "postgres://tgdf:tgdf@localhost/tgdf"

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Run Rubocop
      run: bundle exec rubocop

  brakeman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Run Brakeman
      run: bundle exec brakeman

  rspec:
    runs-on: ubuntu-latest
    services:
        postgres:
          image: postgres
          env:
            POSTGRES_USER: tgdf
            POSTGRES_PASSWORD: tgdf
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - run: yarn install
    - name: Run Migration
      run: bundle exec rake db:migrate
    - name: Run RSpec
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: 095aa40147ca31736e28d41cdec3fc606112be588fa23bbfd155cbdf7f5aafa7
      with:
        coverageCommand: bundle exec rspec
