name: Rails

on:
  push:
    branches:
      - 'main'
      - 'epic/**'
  pull_request:

env:
  RUBY_VERSION: '3.3.2'
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  DATABASE_URL: "postgres://tgdf:tgdf@localhost/tgdf"

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Run Rubocop
      run: bundle exec rubocop

  brakeman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Run Brakeman
      run: bundle exec brakeman

  rspec:
    runs-on: ubuntu-latest
    services:
        postgres:
          image: postgres
          env:
            POSTGRES_USER: tgdf
            POSTGRES_PASSWORD: tgdf
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'yarn'
    - run: yarn install
    - name: Prepare for Test
      run: |
        bundle exec rake assets:precompile
        bundle exec rake db:migrate
    - name: Run RSpec
      run: bundle exec rspec
    - name: Archive RSpec coverage report
      uses: actions/upload-artifact@v3
      with:
        name: simplecov-resultset-rspec
        path: coverage/
        retention-days: 1

  cucumber:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    services:
        postgres:
          image: postgres
          env:
            POSTGRES_USER: tgdf
            POSTGRES_PASSWORD: tgdf
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'yarn'
    - run: yarn install
    - name: Prepare for Test
      run: |
        bundle exec rake assets:precompile
        bundle exec rake db:migrate
    - name: Run Cucumber
      run: bundle exec cucumber -f json -o tmp/cucumber-report.json
    - name: Archive Cucumber coverage report
      uses: actions/upload-artifact@v3
      with:
        name: simplecov-resultset-cucumber
        path: coverage/
        retention-days: 1
    - uses: deblockt/cucumber-report-annotations-action@v1.12
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "tmp/cucumber-report.json"
  report-coverage:
    runs-on: ubuntu-latest
    services:
        postgres:
          image: postgres
          env:
            POSTGRES_USER: tgdf
            POSTGRES_PASSWORD: tgdf
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432
    needs:
      - rspec
      - cucumber
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Download RSpec coverage report
      uses: actions/download-artifact@v3
      with:
        name: simplecov-resultset-rspec
        path: simplecov-resultset-rspec/
    - name: Download Cucumber coverage report
      uses: actions/download-artifact@v3
      with:
        name: simplecov-resultset-cucumber
        path: simplecov-resultset-cucumber/
    - name: Upload coverage report
      if: ${{ github.ref_name == 'main' }}
      uses: paambaati/codeclimate-action@v5.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: bundle exec rake coverage:report
