name: Rails

on:
  push:
    branches:
      - master
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 2.6.6

    services:
        postgres:
          image: postgres
          env:
            POSTGRES_USER: tgdf
            POSTGRES_PASSWORD: tgdf
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run Rubocop
      run: bundle exec rubocop
    - name: Run Brakeman
      run: bundle exec brakeman
    - name: Run Migration
      run: bundle exec rake db:migrate
      env:
        RAILS_ENV: test
        DATABASE_URL: "postgres://tgdf:tgdf@localhost/tgdf"
    - name: Run RSpec
      run: bundle exec rspec
      env:
        RAILS_ENV: test
        DATABASE_URL: "postgres://tgdf:tgdf@localhost/tgdf"
